name: Publish to NPM

on:
  push:
    tags:
      - 'v*' # Triggers the workflow when a new tag starting with 'v' is pushed (e.g. v1.0.1)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24


      - name: Install dependencies
        run: npm install


      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public --provenance

